name: release

on:
  push:
    branches: master
    tags: 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build package
      id: build_package
      run: python3 setup.py sdist bdist_wheel
      if: github.repository == 'cyberreboot/networkml' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    - name: Publish package
      if: ggithub.repository == 'cyberreboot/networkml' && github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_TOKEN }}
